export const industries = [
    { label: "Computer Engineering", value: "computer_engineering" },
    { label: "Information Technology", value: "information_technology" },
    { label: "Cybersecurity", value: "cybersecurity" },
    { label: "Data Science", value: "data_science" },
    { label: "Web Development", value: "web_development" },
    { label: "Mobile Development", value: "mobile_development" },
    { label: "Game Development", value: "game_development" },
    { label: "Artificial Intelligence", value: "artificial_intelligence" },
    { label: "Robotics", value: "robotics" },
    { label: "Government", value: "government" },
    { label: "Municipality", value: "municipality" },
    { label: "University", value: "university" },
    { label: "Automative Industy", value: "automative" },
    { label: "Defence Industy", value: "defence_industry" },
    { label: "Government", value: "government" },
    { label: "Other", value: "other" },
];
